config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'

  get    'register'  => 'users#new'
  get    'login'     => 'sessions#new'
  post   'login'     => 'sessions#create'
#  delete 'logout'    => 'sessions#destroy'
  get 'logout'    => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'users#amazon_login'

  get '/amazon', to: 'promotions#index'

  post '/upload_feed', to: 'users#upload_photofeed'

  post '/nonuser_upload', to: 'users#nonuser_upload'

  # get '/products/:asin', to: 'amznasins#show'

  resources :amznasins, path: :products, param: :asin do
    resources :photofeeds
  end

  resources :users

  get '/oauth', to: 'users#oauth_connect'

  get '/oauth/callback', to: 'users#oauth_callback'

  post '/test', to: 'amznasins#instagram'


  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  	require 'asin'
  	client = ASIN::Client.instance
  	newfeeds = []
  	@photos = Photofeed.all
  	@photos.each do |photo|
  		newfeeds.push(photo.asin)
  	end
  	@items = client.lookup newfeeds
  	# @item_page = items.first.detail_page_url
  	# @item_image_url = items.first.large_image.url
  	# @item_detail = items.first.item_attributes
  end
end

app/views/landing/_carousel.html.erb
<div id="inSlider" class="carousel slide carousel-fade" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#inSlider" data-slide-to="0" class="active"></li>
        <li data-target="#inSlider" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Want to help<br/>
                        small organizations?<br/>
                        You can help with watch<br/>
                        fashion</h1>
                    <p>You can donate without money!</p>
                    <p>
                        <a class="btn btn-lg btn-primary" href="#" role="button">READ MORE</a>
                        <!-- <a class="caption-link" href="#" role="button">Inspinia Theme</a> -->
                    </p>
                </div>
                <div class="carousel-image wow zoomIn">
                    
                </div>
            </div>
            <!-- Set background for slide in css -->
            <div class="header-back one"></div>

        </div>
        <div class="item">
            <div class="container">
                <div class="carousel-caption blank">
                    <h1>What?!<br/> Donate without money!</h1>
                    <p>Posting photos today!</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
                </div>
            </div>
            <!-- Set background for slide in css -->
            <div class="header-back two"></div>
        </div>
    </div>
    <a class="left carousel-control" href="#inSlider" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#inSlider" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

app/views/landing/_navigation.html.erb
<div class="navbar-wrapper">
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header page-scroll navbar-collapse-width">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/"> ZOESH </a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a class="page-scroll" href="/">Home</a></li>
                        <li><a class="page-scroll" href="/#featured">Editor Picks</a></li>
                        <li><a class="page-scroll" href="/#popular">Hot</a></li>
                        <% if current_user %>
                            <li><a class="page-scroll" href="/users/<%= current_user.id %>">Profile</a></li>
                            <li><%= link_to "Logout", logout_path, class: "page-scroll", :method => 'delete' %></li>
                        <% else %>
                            <li><%= link_to "Login", login_path, class: "page-scroll" %></li>
                            <li><%= link_to "Sign up", register_path, class: "page-scroll" %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
</div>

app/views/landing/index.html.erb
<%= render 'navigation' %>
<%= render 'carousel' %>

<div class="container">
  <div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Featured Dresses</h2>
    </div>
  </div>
  <div class="layout_block"></div>

  <div class="row">
       <%= render 'promotions/product_detail' %>
  </div>
</div>

<% content_for :javascript do %>

<script type="text/javascript">
$(function() {

    $('body').addClass('landing-page');
    $('body').attr('id', 'page-top');

    $('body').scrollspy({
        target: '.navbar-fixed-top',
        offset: 80
    });

    // Page scrolling feature
    $('a.page-scroll').bind('click', function(event) {
        var link = $(this);
        $('html, body').stop().animate({
            scrollTop: $(link.attr('href')).offset().top - 50
        }, 500);
        event.preventDefault();
    });

    var cbpAnimatedHeader = (function() {
        var docElem = document.documentElement,
                header = document.querySelector( '.navbar-default' ),
                didScroll = false,
                changeHeaderOn = 200;
        function init() {
            window.addEventListener( 'scroll', function( event ) {
                if( !didScroll ) {
                    didScroll = true;
                    setTimeout( scrollPage, 250 );
                }
            }, false );
        }
        function scrollPage() {
            var sy = scrollY();
            if ( sy >= changeHeaderOn ) {
                $(header).addClass('navbar-scroll')
            }
            else {
                $(header).removeClass('navbar-scroll')
            }
            didScroll = false;
        }
        function scrollY() {
            return window.pageYOffset || docElem.scrollTop;
        }
        init();

    })();


});

</script>

<% end %>