config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'

  get    'register'  => 'users#new'
  get    'login'     => 'sessions#new'
  post   'login'     => 'sessions#create'
#  delete 'logout'    => 'sessions#destroy'
  get 'logout'    => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'users#amazon_login'

  get '/amazon', to: 'promotions#index'

  post '/upload_feed', to: 'users#upload_photofeed'

  post '/nonuser_upload', to: 'users#nonuser_upload'

  # get '/products/:asin', to: 'amznasins#show'

  resources :amznasins, path: :products, param: :asin do
    resources :photofeeds
  end

  resources :users

  get '/oauth', to: 'users#oauth_connect'

  get '/oauth/callback', to: 'users#oauth_callback'

  post '/test', to: 'amznasins#instagram'


  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token

	before_save { self.email = email.downcase }
	validates :name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
										format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_senstivie: false }
	has_secure_password
	validates :password, length: { minimum: 6 }

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
	end

	def User.new_token
	  SecureRandom.urlsafe_base64
	end

	def remember
	  self.remember_token = User.new_token
	  update_attribute(:remember_digest, User.digest(remember_token))
	end

	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	def self.from_omniauth(auth_hash, current_user)
		# check if the login user is in DB, if not, create a new account.
		user = User.find(current_user.id)
		user.real_name = auth_hash['info']['name']
		user.amzn_email = auth_hash['info']['email']
		user.oauth_token = auth_hash['credentials']['token']
		user.save!
		user
	end

	has_many :photofeeds

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  include AmznasinsHelper

  def new
  	@user = User.new
    @user.cashback = 0.0
  @user.click = 0
    @admin_page = false
  end

  def show
  	@user = User.find(params[:id])
    @photofeed = Photofeed.new
    photos = @user.photofeeds
    @user_zoeshes = [] 
    photos.count == 0 ? @user_zoeshes : @user_zoeshes.push(photos.first)
    photos.each_with_index do |photo, idx|
      if idx - 1 >= 0
        if photo.asin != photos[idx-1].asin
          @user_zoeshes.push(photo)
        end
      end
    end
    @zoeshes = @user_zoeshes.count
  end

  def upload_photofeed
    require 'asin'
    client = ASIN::Client.instance

    @photofeed = Photofeed.new(photofeed_params)
    @photofeed.user = User.find(current_user.id)
    @photofeed.amznasin = AmznasinsHelper.new_asin(@photofeed.asin)
    if params[:photofeed][:photo].nil?
      @product = client.lookup(params[:photofeed][:asin])
      @photofeed.photo = @product.first.large_image.url
    end

    if @photofeed.save
      redirect_to "/products/#{params[:photofeed][:asin]}/photofeeds", notice: "The Photofeed #{@photofeed.asin} has been uploaded."
    else
      redirect_to "/products/#{params[:photofeed][:asin]}/photofeeds", notice: "The failed."
    end
  end

  def nonuser_upload
    @photofeed = Photofeed.new(photofeed_params)
    if current_user
      user_id = current_user.id
    else
      user_id = 2
    end
    @photofeed.user = User.find(user_id)
    @photofeed.amznasin = AmznasinsHelper.new_asin(@photofeed.asin)
    if params[:photofeed][:photo].nil?
      @product = client.lookup(params[:photofeed][:asin])
      @photofeed.photo = @product.first.large_image.url
    end

    if @photofeed.save
      redirect_to "/products/#{params[:photofeed][:asin]}/photofeeds", notice: "The Photofeed #{@photofeed.asin} has been uploaded."
    else
      redirect_to "/products/#{params[:photofeed][:asin]}/photofeeds", notice: "The failed."
    end

  end

  def amazon_login
    if current_user
      # request.env['omniauth.auth'] contains the Authentication Hash with all the data about a user
      @user = User.from_omniauth(request.env['omniauth.auth'], current_user)
      # session[:user_id] = @user.id
      flash[:success] = "Successfully login."
    else
      flash[:warning] = "Please try again, we failed to authenticate you"
    end
    redirect_to root_path
  end

  def create
  	@user = User.new(user_params)    # Not the final implementation!
    if @user.save
      log_in @user
    	flash[:success] = "Welcome to Zoesh"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def photofeed_params
      params.require(:photofeed).permit(:asin, :photo, :description, :user_id)
    end

end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
	
end

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="login_page">
    <div class="middle-box text-center loginscreen   animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">IN+</h1>

            </div>
            <h3>Register to FundingWithoutMoney</h3>
            <p>Create account to see it in action.</p>

            <%= form_for @user, :html => {:class => "m-t" } do |f| %>
            	<%= render 'shared/error_messages' %>
            	<div class="form-group">
            		<%= f.text_field :name, class: "form-control", :placeholder => "Name", :required => true %>
            	</div>
            	<div class="form-group">
            		<%= f.text_field :email, class: "form-control", :placeholder => "abc@example.com", :required => true %>
            	</div>
                <div class="form-group">
                     <%= f.select :account_type, ['organization', 'individual']%>
                </div>
            	<div class="form-group">
            		<%= f.password_field :password, class: "form-control", :placeholder => "password", :required => true %>
            	</div>
            	<div class="form-group">
            		<%= f.password_field :password_confirmation, class: "form-control", :placeholder => "confirm password", :required => true %>
            	</div>
           		<%= f.submit "Register", class: "btn btn-primary block full-width m-b" %>
           	<% end %>
            <p class="text-muted text-center"><small>Already have an account?</small></p>
            <%= link_to "Login", login_path, class: "btn btn-sm btn-white btn-block" %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:username, @user.name ) %>
<%= render 'landing/navigation' %>

<div class="layout_block"></div>
<div class="container">
<div class="wrapper wrapper-content">
<div class="row animated fadeInRight">
    <div class="col-md-4">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Feeds</h5>
            </div>
            <div>
                <div class="ibox-content no-padding border-left-right">
                    <img alt="image" class="img-responsive" src="<%= image_path('profile_big.jpg') %>">
                </div>
                <div class="ibox-content profile-content">
                    <h4><strong><%= @user.name %></strong></h4>
                    <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
                    <h5>
                        About me
                    </h5>
                    <p>
                        <%= @user.description %>
                    </p>
                    <div class="row m-t-lg">
                        <div class="col-md-4">
                            
                            <h5><strong><%= @zoeshes %></strong> Zoeshes </h5>
                        </div>
                        <div class="col-md-4">
                            
                            <h5><strong><%= @user.visit %></strong> Clicks </h5>
                        </div>
                        <div class="col-md-4">
                            
                            <h5><strong>$<%= @user.funding %></strong> Cashback </h5>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Activites</h5>
                <div class="ibox-tools">
                </div>
            </div>
            <div class="ibox-content">
                <% if current_user %>
                   <% if current_user.id == @user.id %>
                        <div class="row">
                            <div class="col-lg-4">
                        		<%= form_for @photofeed, :url => upload_feed_path, html: { multipart: true } do |f| %>
                        		  <%= f.label :asin %> <br>
                        		  <%= f.text_field :asin %> <br>
                        		  <%= f.label :description %> <br>
                        		  <%= f.text_field :description %> <br>
                                  <br>
                        		  <%= f.file_field :photo, :class => "file_upload", :accept => "image/*" %> 
                        		  <%= f.submit "Post", class: "btn btn-primary" %>
                        		<% end %>
                            </div>
                            <div class="col-lg-6 col-lg-offset-2">
                                <div class="image-crop" style="display:none;">
                                    <img src="<%= image_path('p3.jpg') %>">
                                </div>
                                <div class="img-preview img-preview-lg"></div>
                            </div>
                        </div>
                        <div class="layout_block"></div>
                    <% end %>
                <% end %>

                <div class="row">

                    <% @user_zoeshes.each_with_index do |item, index| %>
                        <% if index % 3 == 0 %>
                          <div class="row">
                        <% end %>
                          <div class="zoesh_sm_box col-lg-4">
                             <div class="zoesh_box_image">
                                <% require 'asin' %>
                                <% client = ASIN::Client.instance %>
                                <% @product = client.lookup item.asin %>
                                    <% product_photo = Amznasin.find_by(asin:item.asin) %>
                                    <a href="/products/<%= product_photo.asin%>"><img src="<%= item.photo %>"></a>
                             </div>
                             <div class="zoesh_sm_box_desc">
                                   <span class="product-price">
                                      <% if @product.first.item_attributes.list_price %>
                                      <%= @product.first.item_attributes.list_price.formatted_price %> 
                                      <% else %>
                                      Click to see!
                                      <% end %>
                                   </span>
                                 <small class="text-muted"><%= @product.first.item_attributes.brand %></small>
                                 <a href="<%= @product.first.detail_page_url %>" class="product-name product_sm_title"> <%= @product.first.item_attributes.title %> </a>

                                 <div class="small m-t-xs">
                                     
                                 </div>
                                 <div class="row pull-right favor_bar">
                                        <button class="btn btn-danger btn-circle btn-outline" type="button"><i class="fa fa-heart"></i>
                                     </button>
                                     <a href="<%= @product.first.detail_page_url %>" class="btn btn-xs btn-outline btn-info">Add to Cart</i></a>
                                 </div>
                              </div>
                         </div>
                         <% if (index + 1) % 3 == 0 || index + 1 == @user_zoeshes.count %>
                          </div>
                          <div class="layout_block"></div>
                         <% end %>
                    <% end %>
            </div>
        </div>

    </div>
</div>
</div>
</div>


<% content_for :javascript do %>

<script type="text/javascript">


$(function() {


});

</script>

<% end %>