config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'

  get    'register'  => 'users#new'
  get    'login'     => 'sessions#new'
  post   'login'     => 'sessions#create'
#  delete 'logout'    => 'sessions#destroy'
  get 'logout'    => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'users#amazon_login'

  get '/amazon', to: 'promotions#index'

  post '/upload_feed', to: 'users#upload_photofeed'

  post '/nonuser_upload', to: 'users#nonuser_upload'

  # get '/products/:asin', to: 'amznasins#show'

  resources :amznasins, path: :products, param: :asin do
    resources :photofeeds
  end

  resources :users

  get '/oauth', to: 'users#oauth_connect'

  get '/oauth/callback', to: 'users#oauth_callback'

  post '/test', to: 'amznasins#instagram'


  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/amznasin.rb
class Amznasin < ActiveRecord::Base
	has_many :photofeeds, dependent: :destroy
end

app/controllers/amznasins_controller.rb
class AmznasinsController < ApplicationController
	include SessionsHelper

	def show
		asin = params[:asin]
		@asin_products = Amznasin.find_by(asin:asin).photofeeds.first
		require 'asin'
  	client = ASIN::Client.instance
  	@product = client.lookup asin
	end

	def instagram
	  require "sinatra"
	  require "instagram"

	  Instagram.configure do |config|
	    config.client_id = ENV['INSTA_CLIENT_ID']
	    config.client_secret = ENV['INSTA_CLIENT_SECRET']
	  end
	  client = Instagram.client(:access_token => ENV['INSTA_ACCESS_TOKEN'])

	  tags = Instagram.tag_search(params["/test"]["tags"])
	  tags[0].name  
	  tags[0].media_count
	  for media_item in client.tag_recent_media(tags[0].name).first(5)
	     asin = Photofeed.new(asin:params["/test"]["asin"])
	     asin.description = "instagram"
	     asin.photo = media_item.images.thumbnail.url
	     asin.user = User.find(current_user.id)
	     asin.amznasin = Amznasin.find_by(asin:params["/test"]["asin"])
	     asin.save
	  end

	  redirect_to "/products/#{params["/test"]["asin"]}/photofeeds"
	end

end

app/helpers/amznasins_helper.rb
module AmznasinsHelper
	def self.new_asin(asin)
		new_asin = Amznasin.find_by(asin:asin)
		if !new_asin
			new_asin = Amznasin.create!(asin:asin)
		end
		new_asin
	end
end

app/views/amznasins/_instagram_search.html.erb
<% if current_user %>
  <% if current_user.id == @asin_products.user_id %> 
    <div class="row">
      <%= form_for '/test', :url => '/test', :html => {:class => "form-group"} do |f| %>
        <span class="col-sm-2">
          <%= f.label "Instagram Tag", class:"control-label" %>
        </span>
        <span class="col-sm-10">
              <%= f.text_field :asin, :value => params[:asin], class:"hidden" %>
          <div class="input-group">
              <%= f.text_field :tags, class:"form-control" %>
            <span class="input-group-btn">
              <%= f.submit "Instagram!", class:"btn btn-primary" %>
            </span>
          </div>
        </span> 
      <% end %>
    </div>
  <% end %>
<% end %>

<div class="layout_block"></div>

<div class="row">
  <div class="col-sm-12">
    <div class="">
      <%= render 'upload' %>
    </div>
  </div>
</div>

app/views/amznasins/_product.html.erb
 <div class="zoesh_box_image">
     <a href="<%= @product.first.detail_page_url %>"><img src="<%= @asin_products.photo %>"></a>
  </div>
 <div class="zoesh_box_desc">
      <span class="product-price">
         <% if  @product.first.item_attributes.list_price %>
         <%=  @product.first.item_attributes.list_price.formatted_price %> 
         <% else %>
         Click to see!
         <% end %>
      </span>
    <small class="text-muted"><%= @product.first.item_attributes.brand %></small>
    <a href="<%= @product.first.detail_page_url %>" class="product-name"> <%= @product.first.item_attributes.title %></a>

    <div class="small m-t-xs">
        
    </div>
    <div class="row pull-right favor_bar">
       <button class="btn btn-danger btn-circle btn-outline" type="button"><i class="fa fa-heart"></i>
       </button>
       <a href="<%= @product.first.detail_page_url %>" class="btn btn-xs btn-outline btn-info">Add to Cart</i></a>
    </div>
 </div>

app/views/amznasins/_upload.html.erb
      <%= form_for :photofeed, :url => nonuser_upload_path, :html => {:class => "form-group"} do |f| %>
        <p> Want to upload a photo ? </p>
        <%= f.label "Description", class:"control-label" %>
        <%= f.text_field :asin, :value => params[:asin], class:"hidden" %>
        <%= f.text_field :description, class: "form-control"%>
        <span class="btn btn-info btn-outline btn-file">
          <label for="file">Browse</label><%= f.file_field :photo, :accept => "image/*" %>
        </span>
        <%= f.submit "Upload Photo", class: "btn btn-primary" %>
      <% end %>

app/views/amznasins/old_show.html.erb
<%= render 'landing/navigation' %>
<div class="layout_block"></div>
<div class="layout_block"></div>
<div class="container">
       		<% @asin_products.each_with_index do |product, index| %>
       	      <% if index % 3 == 0 %>
                <div class="row">
              <% end %>
                  <div class="zoesh_box col-lg-4">
                     <div class="zoesh_box_image">
         		         		<a href="<%= @product.first.detail_page_url %>"><img src="<%= product.photo %>"></a>
       		           </div>
       		         <div class="zoesh_box_desc">
       		               <span class="product-price">
                             <% if  @product.first.item_attributes.list_price %>
                             <%=  @product.first.item_attributes.list_price.formatted_price %> 
                             <% else %>
                             Click to see!
                             <% end %>
       		               </span>
       		             <small class="text-muted"><%= @product.first.item_attributes.brand %></small>
       		             <a href="<%= @product.first.detail_page_url %>" class="product-name"> <%= @product.first.item_attributes.title %> </a>

       		             <div class="small m-t-xs">
       		                 
       		             </div>
       		             <div class="row pull-right favor_bar">
       		             		<button class="btn btn-danger btn-circle btn-outline" type="button"><i class="fa fa-heart"></i>
       		                </button>
       		                <a href="<%= @product.first.detail_page_url %>" class="btn btn-xs btn-outline btn-info">Add to Cart</i></a>
       		             </div>
       		          </div>
       		     </div>
               <% if (index + 1) % 3 == 0 || index + 1 == @asin_products.count %>
                </div>
                <div class="layout_block"></div>
        <% end %>
    <% end %>               
</div>

app/views/amznasins/show.html.erb
<%= render 'landing/navigation' %>
<div class="layout_block"></div>
<div class="layout_block"></div>
<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <%= render 'product' %>
    </div>
    <div class="col-lg-8">
      <%= render 'instagram_search' %>
    </div>
    </div>
  </div>              
</div>